### PR TITLE
Prettier formatting

### PR DESCRIPTION
**Pull request by mattdesl**
- deleted `lib/gui.js` file which wasn't referenced by anything
- deleted `examples/experimental/webgl-2d-ideas.js` which was just random notes
- added prettier to package.json and a new run script command
- ran on all JS source files

To consider: having a git commit hook so that pushes cannot be made without proper formatting.

### CODE REVIEW

**Comment by mattdesl** [comment]
@alvinometric hopefully nothing here messes things up. I'm using Prettier extension in VSCode so that it formats on save, just fyi.

**Comment by alvinometric** [comment]
omg not at all this was the next thing on my list! Thank you so much

**Comment by sfrieson** [comment]
> To consider: having a git commit hook so that pushes cannot be made without proper formatting.

Do you want any help with this?

**Comment by alvinometric** [comment]
@sfrieson If you can make a quick PR, go for it!

**Comment by sfrieson** [comment]
[Added.](https://github.com/mattdesl/canvas-sketch/pull/191)

**Pull request merged**
