### PR TITLE
Modernisation

### PR DESCRIPTION
**Pull request by alvinometric**
Hello, 
This is a PR to clean up `canvas-sketch` itself, and two things happen here.
- Updated microbundle to latest
- Removed unused dependencies

### CODE REVIEW

**Comment by mattdesl** [comment]
:+1: Looks good! Did you have any trouble running/building it locally with these changes?

**Comment by alvinometric** [comment]
It's building and running, but I've not managed to symlink it to test these changes yet

**Comment by alvinometric** [comment]
I finally managed to test it locally, and added more improvements

**Comment by mattdesl** [comment]
Merged! Will keep it on master for a bit as we continue to tackle other things before we cut a new release, if that sounds good?

**Comment by alvinometric** [comment]
All good, thanks for mergin!

**Pull request merged**
